export const Technologies = () => {
  return (
    <div className="flex flex-wrap gap-2">
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"
        alt="TypeScript"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
        alt="JavaScript"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg"
        alt="Java"
        className="h-12"
      />
      <img
        src="https://res.cloudinary.com/dttpgbmdx/image/upload/v1745953822/icon-express_foa4dc.png"
        alt="Express"
        className="h-12"
      />
      <img
        src="https://res.cloudinary.com/dttpgbmdx/image/upload/v1745926364/nodejsicon_dioqsc.png"
        alt="Node.js"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"
        alt="MongoDB"
        className="h-12"
      />
      <img
        src="https://res.cloudinary.com/dttpgbmdx/image/upload/v1745927113/supabase-icon_w2upjk.png"
        alt="Supabase"
        className="h-12"
      />
      <img
        src="https://mongoosejs.com/docs/images/mongoose5_62x30_transparent.png"
        alt="Mongoose"
        className="w-16"
      />

      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
        alt="PostgreSQL"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg"
        alt="MySQL"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg"
        alt="HTML"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg"
        alt="CSS"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg"
        alt="Bootstrap"
        className="h-12"
      />
      <img
        src="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
        alt="Tailwind CSS"
        className="h-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
        alt="React"
        className="h-12"
      />
      <img
        src="https://res.cloudinary.com/dttpgbmdx/image/upload/v1745432721/react-query-seeklogo_axk8ly.png"
        alt="Tanstack"
        className="h-12"
      />
      <img
        src="https://axios-http.com/assets/logo.svg"
        alt="Axios"
        className="h-12 w-12"
      />
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
        alt="Git"
        className="h-12"
      />
      <img
        src="https://res.cloudinary.com/dttpgbmdx/image/upload/v1745926580/githubicon_om10uz.png"
        alt="GitHub"
        className="h-12"
      />
      <img
        src="https://res.cloudinary.com/dttpgbmdx/image/upload/v1745926941/postman_inzdip.png"
        alt="Postman"
        className="h-14"
      />
      <img
        src="https://www.svgrepo.com/show/375433/firestore.svg"
        alt="Firestore"
        className="h-12"
      />
    </div>
  );
};
